name: supabase_codegen_example
description: "Supabase Codegen Example Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.19.0

  supabase_codegen_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  meta: 1.16.0
  supabase_codegen:
    path: ../../supabase_codegen

flutter:
  uses-material-design: true
  assets:
    - config.env
