name: supabase_codegen_flutter
description: Supabase Codegen Flutter Package
homepage: https://github.com/Khuwn-Soulutions/supabase_codegen
version: 3.0.1
repository: https://github.com/Khuwn-Soulutions/supabase_codegen/tree/main/packages/supabase_codegen_flutter
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  meta: ^1.16.0
  path: ^1.9.1
  supabase_codegen: ^3.0.1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

dependency_overrides:
  # Flutter test requires 1.16.0
  meta: ^1.16.0
  # override the test version in core package to ensure flutter test compatibility
  test: ^1.25.15

executables:
  generate_types:
  add_codegen_functions:
